eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8071
spring:
  application:
    name: eurekaclient
  datasource:
    url: jdbc:mysql://47.96.232.71:3306/dump_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: meina2019
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  zipkin:
#   zipkin链路服务地址配置,配了消息地址就不需要了，直接从mq获取
#     base-url: http://localhost:9411
    sender:
      type: rabbit
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
logging:
  path: /var/logs #配置日志生成路径
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
